### PR TITLE
Chinese Translation

### PR DESCRIPTION
**Pull request by qsefthuopq**

### CODE REVIEW

**Comment by Redblueflame** [comment]
Hi @qsefthuopq !
Thanks for your translation !
If you want, you can also translate the patchouli book for a full translation.
Don't hesitate to leave a comment here if you need any help 😉

**Comment by qsefthuopq** [comment]
The texts in book aren't listed in the lang file,I can't translate them for now.

**Comment by Redblueflame** [comment]
The recommended way to add translation for the patchouli book is to duplicate the en_us folder [here](https://github.com/evolzmc/herbocraft/tree/master/src/main/resources/data/herbocraft/patchouli_books/main-book), and do the translation here. I'll be adding a translation string for the main menu page, that is the only string that can't be translated yet, if you can send the translation here, I'll be adding it to the translation file after my fix.

**Comment by Redblueflame** [comment]
Seems good to me. @qsefthuopq is everything finished? If it is, can you mention me so I can merge it ?

**Pull request merged**
